[package]
name = "mge-game"
version.workspace = true
edition.workspace = true

[[bin]]
name = "mge-game"
path = "src/main.rs"

[dependencies]
mge-core = { workspace = true }
mge-sim = { workspace = true }
mge-world = { workspace = true }
mge-render = { workspace = true }
mge-platform = { workspace = true }
mge-runtime = { workspace = true }
glam = { workspace = true }
hecs = { workspace = true }
image = { workspace = true }
serde = { workspace = true }
ron = { workspace = true }
tracing = { workspace = true }
winit = { workspace = true }
egui = { workspace = true }
egui-winit = { workspace = true }
kira = { workspace = true }
