[package]
name = "mge-world"
version.workspace = true
edition.workspace = true

[dependencies]
mge-core = { workspace = true }
mge-sim = { workspace = true }
glam = { workspace = true }
noise = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
ron = { workspace = true }
tracing = { workspace = true }
